baseURL = "https://hrecos2.netlify.com/"
languageCode = "en-us"
title = "HRECOS"
theme = "hugo-serif-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Hudson River Environmental Conditions Observation System"
    meta_og_title = "HRECOS"
    meta_og_type = "website"
    meta_og_url = "https://hrecos2.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Hudson River Environmental Conditions Observation System"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2

[[menu.main]]
	name = "Testimonials"
	url = "/testimonials/"
	weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
    
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
